DROP TABLE STUDENT;
DROP TABLE STUDENT2;

CREATE TABLE STUDENT (
    name    VARCHAR(100),
    age     INT NOT NULL
);

INSERT INTO STUDENT VALUES ('Namig', 13);
INSERT INTO STUDENT VALUES ('Maxim', 34);
INSERT INTO STUDENT VALUES ('Z', 1);


CREATE TABLE STUDENT2 (
    name    VARCHAR(100),
    age     INT NOT NULL
);

INSERT INTO STUDENT2 VALUES ('Anna', 13);
INSERT INTO STUDENT2 VALUES ('Katya', 34);
INSERT INTO STUDENT2 VALUES ('Katya2', 34);
INSERT INTO STUDENT2 VALUES ('Anton', 24);

SELECT * FROM STUDENT, STUDENT2;